// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu8JnxJzxuXxb2oKhgIRG7jBwPnb2d5J0',
    appId: '1:72860799529:web:2ee942ec7824d830f48238',
    messagingSenderId: '72860799529',
    projectId: 'patrol-demo-test',
    authDomain: 'patrol-demo-test.firebaseapp.com',
    storageBucket: 'patrol-demo-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKp-OTO3LGcOqa5VG4qjTYYVIOOqoU5lE',
    appId: '1:72860799529:android:28cb118051c0eaf7f48238',
    messagingSenderId: '72860799529',
    projectId: 'patrol-demo-test',
    storageBucket: 'patrol-demo-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHRVrkXnr2mkbWiI_YnfqV3aPlF9nVN3s',
    appId: '1:72860799529:ios:36098e1590acfc41f48238',
    messagingSenderId: '72860799529',
    projectId: 'patrol-demo-test',
    storageBucket: 'patrol-demo-test.firebasestorage.app',
    iosBundleId: 'com.example.patrolTestDemo',
  );
}
